export const WHITELABEL_ID = 188;
export const PP_API_URL = 'https://content.progressplay.net/api23/api/';
export const PP_PROMOTIONS_API = `${PP_API_URL}PromotionsInfo?whitelabelId=${WHITELABEL_ID}&country=`;
export const WP_API = 'https://staging4.casimboo.com/wp-json/wp/v2/';
export const KV_REST = "https://access-wprestapi.tech1960.workers.dev/";
export const PP_LOBBY_LINK = 'https://casimboo.casino-pp.net/';
export const CF_GEO_WORKER = 'https://cf-geo-lookup.tech1960.workers.dev/';
export const KV_GAMES = "https://access-ppgames.tech1960.workers.dev/";
export const KV_SUPPORTED_COUNTRIES = "https://access-supportedcountries.tech1960.workers.dev/";
export const REST_COUNTRY_KV = "https://access-restcountries.tech1960.workers.dev/";
export const IGP_SUPPORTED_COUNTRIES = "https://igp-supported-countries.tech1960.workers.dev/";
export const FILTERED_BY_NAME_KV = "https://access-filterbyname.tech1960.workers.dev/";
export const KV_TRANSLATIONS ="https://access-translations.tech1960.workers.dev/";